#!/usr/bin/env bash
# helix-loop-7317 — build & smoke test driver generated by PushForge Engine.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
echo "[helix-loop-7317] root=$ROOT"

if command -v go >/dev/null; then (cd "$ROOT" && go build ./... 2>/dev/null || true); fi
if command -v cargo >/dev/null; then (cd "$ROOT" && cargo check --quiet 2>/dev/null || true); fi
if command -v python3 >/dev/null; then (cd "$ROOT" && python3 -m compileall -q . || true); fi

echo "[helix-loop-7317] smoke complete"
